# Paths to exclude from linting.
excluded:
  - Pods
  - iOSEngineerCodeCheckTests
  - iOSEngineerCodeCheckUITests
  - .git
  - .github
  - fastlane # Add this if you have fastlane in your project root, otherwise omit
  - Carthage # Add this if you use Carthage, otherwise omit

# Paths to include (lint only these paths)
# If 'excluded' is set, 'included' is often not strictly necessary unless you want to be very specific
# included:
#   - iOSEngineerCodeCheck # Lint only the main source folder

# You can also customize rules here. For now, let's just focus on exclusions.
# For example, to disable the 'force_cast' rule:
# disabled_rules:
#   - force_cast
